config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy' end
  root to: "articles#index"

  resources :users, only: [ :index, :show] do
    resources :searches, only: [ :index, :show, :new, :create]
  end
  resources :articles, only: [ :index, :show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  def self.search(params)
    if params[:query].blank?
      all
    elsif where(
      'title LIKE ? OR content LIKE ? ',
      "%#{sanitize_sql_like(params[:query])}%", "%#{sanitize_sql_like(params[:query])}%"
    ).empty?
      none
    else
      where(
        'title LIKE ? OR content LIKE ? ',
        "%#{sanitize_sql_like(params[:query])}%", "%#{sanitize_sql_like(params[:query])}%"
      )
    end
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :content, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  validates :searching_for, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :searches, dependent: :destroy
  has_many :articles, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end

  def after_sign_out_path_for(_scope)
    root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.search(params)
    @search = current_user.searches.new(searching_for: params[:query], user_id: current_user.id)
    optimize_search
  end

  def optimize_search
    if @search.searching_for
      @search.searching_for = if @search.searching_for[0] == ' ' || @search.searching_for[-1] == ' '
                                @search.searching_for.strip!
                              else
                                @search.searching_for
                              end
    end

    return unless @search.searching_for and !@search.searching_for.empty?

    if Search.exists?(searching_for: @search.searching_for)
      @original_search = Search.find_by(searching_for: @search.searching_for)
      @original_search.frequency += 1
      @original_search.save
    else
      @search.save
    end
  end

  def show
    @article = Article.find params[:id]
  end

  def new
    @article = Article.new
    respond_to do |format|
      format.html { render :new, locals: { article: @article } }
    end
  end

  def article_params
    params
      .require(:article)
      .permit(:title, :content)
      .merge(user_id: params[:user_id])
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to articles_path(@article.user_id, @article.id)
    else
      render :new
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @searches = current_user.searches
  end

  def show
    @search = Search.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
    <div id="<%= article %>">
        <p class="text-lg leading-loose">
        <%= link_to article.title, article_path(article), class: "text-blue-600 hover:text-orange-700" %>
        </p>
    </div>
<% end %>

app/views/articles/index.html.erb
<div class="px-6 w-full mr-6 mt-12 ">
<%= form_tag articles_path, method: "GET", remote: true ,data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search", action: "input->search#submit"} do %>
    <%= text_field_tag "query", nil, placeholder: "Search ..." %>
    <%= submit_tag "Search" %>
<% end %>


<div class="my-6">
  <%=  turbo_frame_tag "search-results" do %>
    <%= render "articles",  articles: @articles  %>
  <% end %>
</div>

<%= link_to "New article", new_article_path, class: " px-6 py-2.5 mb-6 mt-6 w-1/3 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
</div>

app/views/articles/new.html.erb
<div class="mt-8">
  <div class="min-w-screen flex pt-1 justify-center font-sans overflow-hidden">
    <div class="block rounded-lg shadow-lg bg-white px-6 py-8 md:px-12 lg:w-1/2 h-full mb-5 ">
      <h2 class="">Add New Article</h2>
      <%= form_with model: @article, url: articles_path, method: :post,  local: true, scope: :article,data: { turbo: false }  do |form| %>
        <div class="relative ">
          <%= form.label :title, class: "leading-7 text-sm text-gray-400" %>
          <%= form.text_field :title, autofocus: true,class: "form-control block w-full px-3 py-1.5 mb-4 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
        </div>
        <div class="relative ">
          <%= form.label :content, class: "leading-7 text-sm text-gray-400" %>
          <%= form.text_area :content, autofocus: true, rows: "10", cols: "40", class: "form-control block w-full px-3 py-1.5 mb-4 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
        </div>
        <div class="actions flex justify-between">
          <%= form.submit "Save", class: " px-6 py-2.5 mb-6 w-1/3 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
          <%= link_to 'Back', url_for(:back), class: "text-center px-6 py-2.5 mb-6 w-1/3 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
        </div>
      <% end %>
    </div>
  </div>
  <% if flash[:notice] %>
    <div class="alert-pos" id="notice"><%= flash[:notice] %></div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="overflow-x-auto">
  <div class="min-w-screen min-h-screen bg-gray-100 flex pt-20 justify-center bg-gray-100 font-sans overflow-hidden">
    <div class="w-full lg:w-5/6">
      <div class="block rounded-lg shadow-lg bg-white px-6 py-12 md:px-12 ">
        <div class="actions text-center mb-6">
          <strong>Article title: </strong><%= @article.title  %>
        </div>
        <div class="actions  mb-6">
          <div><strong>content: </strong></div>
          <p><%= @article.content %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class=" bg-gray-100">
    <% if current_user %>
      <%= render partial: "shared/navbar" %>
    <%end%>
    <main >
      <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen  flex justify-center font-sans overflow-hidden">
          <div class="w-full ">
            <div class="ml-5 container w-full flex text-right mt-3 absolute z-50 lg:w-1/3">
              <% if notice %>
                  <strong class="mb-5">Notice: </strong> <%= notice %>
              <%end%>
              <% if  alert %>
                  <strong class="mb-5">Alert: </strong> <%= alert %>
              <%end%>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/searches/index.html.erb
<div class="overflow-x-auto">
  <div class="min-w-screen min-h-screen bg-gray-100 flex pt-20 justify-center bg-gray-100 font-sans overflow-hidden">
    <div class="w-full lg:w-5/6">
    
      <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-max w-full table-auto">
          <thead>     
          <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-left">Search</th>
              <th class="py-3 px-6 text-left">Frequency</th>
          </tr> 
          </thead>
          
          <tbody class="text-gray-600 text-sm font-light">
          <% @searches.order(frequency: :desc).limit(30).each do |search| %>
              <tr class="border-b border-gray-200 hover:bg-gray-100">
                <td class="py-3 px-6 text-left whitespace-nowrap">
                  <div class="flex items-center">
                    <span class="text-gray-900 text-xl leading-tight font-medium px-6 py-6"><%= search.searching_for %></span>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <span class="bg-green-200 text-green-600 py-1 px-3 rounded-full text-xs"><%= search.frequency %></span>
                  </div>
                </td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  

app/views/shared/_navbar.html.erb
<section>

    <nav class="navbar navbar-expand-lg shadow-md py-2 bg-white relative flex items-center w-full justify-between mb-6">
      <div class="px-6 w-full flex flex-wrap items-center justify-between">

          <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
            <li class="nav-item">
              <%= link_to "Articles", articles_path, class: "nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out" %>
            </li>
            <li class="nav-item">
              <%= link_to  "Searches Analytics", user_searches_path(current_user, current_user.id), class: "nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"  %>
            </li>
          </ul>
          
        <div class="flex items-center lg:ml-auto">
          
          <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false },class: "inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
        </div>
      </div>
    </nav>

   
  </section>